/*
 * This Java source file was generated by the Gradle 'init' task.
 * MEHMET CAN OZ 161201080
 * BIL 481 HW1
 */
package hw1part2;

import java.lang.reflect.Array;
import java.util.*;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;
import static spark.Spark.get;
import static spark.Spark.post;
import static spark.Spark.port;


public class App {
    public static void main(String[] args) {
       
        //port(Integer.parseInt(System.getenv("PORT")));
        get("/",(req,res)-> "<li> <a href=\"lovemeter\"> LoveMeter</a></li>");
        
        get(
            "/lovemeter",
            (rq,rs) -> {
                Map<String,String> map = new HashMap<String,String>();
                map.put("result","not computed yet");
                map.put("commonHobbies","not found yet");
                return new ModelAndView(map, "lovemeter.moustache");
            },
            new MustacheTemplateEngine()
        );
        post(
            "/lovemeter",
            (rq,res) -> {
                String name1=rq.queryParams("agee1");
                String name2=rq.queryParams("agee2");
                Integer age1=Integer.parseInt( name1);
                Integer age2=Integer.parseInt( name2);
                name1=rq.queryParams("name1");
                name2=rq.queryParams("name2");
                String hobby1=rq.queryParams("hobby1");
                String hobby2=rq.queryParams("hobby2");
                
                java.util.Scanner sc1=new java.util.Scanner(hobby1);
                //sc1.useDelimiter("[;\r\n]+");
                ArrayList<String> hobbyList1=new ArrayList<>(10);
                while(sc1.hasNextLine()){
                    hobbyList1.add(sc1.nextLine());
                }
                sc1.close();

                java.util.Scanner sc2=new java.util.Scanner(hobby2);
                //sc1.useDelimiter("[;\r\n]+");
                ArrayList<String> hobbyList2=new ArrayList<>(10);
                while(sc2.hasNextLine()){
                    hobbyList2.add(sc2.nextLine());
                }
                sc2.close();
                
                ArrayList<String> result = App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2);
                Map<String,String> map=new HashMap<String,String>();
                map.put("result",result.remove(0));
                String dumb = result.toString();
                dumb=dumb.substring(1,dumb.length()-1);
                if(dumb.length()==0)
                    dumb="nothing";
                map.put("commonHobbies",dumb);
                
                return new ModelAndView(map,"lovemeter.moustache");
            }, new MustacheTemplateEngine()
        );

    }
    public static ArrayList<String> loveCalculator(String name1,String name2 , ArrayList<String> hobbyList1, ArrayList<String> hobbyList2, Integer...ages ){
        ArrayList<String> commonHobbies=new ArrayList(10);
        for(String s:hobbyList2){
            if(hobbyList1.contains(s)){
                commonHobbies.add(s);
            }
        }
        ArrayList<String> ret=new ArrayList<String>();
        Integer rate = (ages[0].hashCode()+ages[1].hashCode()+name1.hashCode()+name2.hashCode()+hobbyList1.hashCode()+hobbyList2.hashCode()) % 101;
        rate=(rate>=0)?rate:-rate;
        rate=rate+commonHobbies.size()*5;
        ret.add(rate.toString());
        ret.addAll(commonHobbies);
        //ret.add("\n"+commonHobbies.toString());
        return ret;
    }
}
