/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1part2;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static ArrayList<String> includedStrings(ArrayList<String> analiste, ArrayList<String> listem ){
        ArrayList<String> filtreli=new ArrayList(10);
        //System.out.println("~~ ciktikrali : "+analiste.toString());
        //System.out.println("~~ ciktikrali : "+listem.toString());
        for(String s:listem){

            if(analiste.contains(s)){
                filtreli.add(s);
              //  System.out.println("~~ cikti : "+s);
            }
        }
       // System.out.println("~~ cikti : "+filtreli.toString());
        return filtreli;
    }
}
