/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1part2;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    String name1;
    String name2;
    Integer age1,age2;
    ArrayList<String> hobbyList1;
    ArrayList<String> hobbyList2;
    @BeforeEach void setUp(){
        name1="testname1";
        name2="testname2";
        age1=21;
        age2=20;
        hobbyList1=new ArrayList<>(10);
        hobbyList2=new ArrayList<>(10);
        hobbyList1.add("sport");
        hobbyList1.add("dance");
        hobbyList1.add("tv");
        hobbyList1.add("books");
        hobbyList2.add("sport");
        hobbyList2.add("sculpture");
        hobbyList2.add("ski");
        hobbyList2.add("tv");
    }
    @Test void canFindCommonHobbies(){
        assertTrue(App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2).contains("sport"));
        assertTrue(App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2).contains("tv"));
    }
    @Test void irrelevantHobbiesCheck(){
        assertFalse(App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2).contains("dance"));
        assertFalse(App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2).contains("books"));
        assertFalse(App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2).contains("sculpture"));
    }
   
    @Test void lackOfAge(){
        assertThrows(Exception.class, ()->{
            App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1);
        });
    }
    @Test void consistencyCheck(){
        ArrayList<String> test1=App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2);
        ArrayList<String> test2=App.loveCalculator(name1, name2, hobbyList1, hobbyList2, age1,age2);
        assertEquals( test1.get(0),test2.get(0) );
    }
    
    
}
